version: '3.4'
volumes:
  mysql_data:
  postgresql_data:
#  es_data:
services:
  griffin:
    build:
      context: .
      args:
        - ES_URL                        # elasticsearch, url,
        - S3_ACCESS_KEY                 # this value is defined in .env
        - S3_SECRET_KEY                 # this value is defined in .env
        - S3A_ENDPOINT=s3.amazonaws.com
        - POSTGRESQL_HOSTNAME=postgres  # postgresql, hostname, service postgres
    env_file: .env
    image: 013090004028.dkr.ecr.us-west-2.amazonaws.com/plume-griffin:0.2.7
    hostname: griffin
    links:
      - postgres
    #  - es
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 32122:2122
      - 38088:8088  # yarn rm web ui
      - 33306:3306  # mysql
      - 38042:8042  # yarn nm web ui
      - 39083:9083  # hive-metastore
      - 38998:8998  # livy
      - 38080:8080  # griffin ui
    tty: true
    container_name: griffin
  postgres:
    build: ./postgresql
    image: 013090004028.dkr.ecr.us-west-2.amazonaws.com/plume-postgres:0.2.6
    hostname: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql
    ports:
      - 35432:5432  # postgres
    tty: true
    container_name: postgres
  # es:
  #   image: bhlx3lyx7/elasticsearch
  #   hostname: es
  #   volumes:
  #     - es_data:/usr/share/elasticsearch/data
  #   ports:
  #     - 39200:9200
  #     - 39300:9300
  #   tty: true
  #   container_name: es
